src/Novtehprom.Web.Mvc/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abp.Localization;
using Microsoft.AspNetCore.Mvc;
using Novtehprom.Controllers;
using Novtehprom.Web.Mvc.Models;
using Novtehprom.WepPages.Contacts;

namespace Novtehprom.Web.Mvc.Controllers
{
    /// <summary>
    /// Контроллер для страницы Contacts
    /// </summary>
    public class ContactsController : NovtehpromControllerBase
    {
        public ContactsController(IContactsAppService contactsAppService)
        {
            _contactsAppService = contactsAppService;
        }

        private readonly IContactsAppService _contactsAppService;
        public async Task<IActionResult> IndexAsync()
        {
            var contDto = await _contactsAppService.GetContacts();
            var model = new ContactsViewModel(contDto);
            ViewBag.RetFromLoginUrl = @"/Contacts/Index/";
            return View(model);
        }
    }
}

src/Novtehprom.Web.Mvc/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Novtehprom.Controllers;

namespace Novtehprom.Web.Mvc.Controllers
{
    public class ProgramController : NovtehpromControllerBase
    {
        /// <summary>
        /// Стоимость ПО
        /// </summary>
        /// <returns></returns>
        public IActionResult Cost()
        {
            ViewBag.RetFromLoginUrl = @"/Program/Cost/";
            return View();
        }
        /// <summary>
        /// Сроки разработки ПО
        /// </summary>
        /// <returns></returns>
        public IActionResult Timeframe()
        {
            ViewBag.RetFromLoginUrl = @"/Program/Timeframe/";
            return View();
        }

        /// <summary>
        /// Качество разработки ПО
        /// </summary>
        /// <returns></returns>
        public IActionResult Quality()
        {
            ViewBag.RetFromLoginUrl = @"/Program/Quality/";
            return View();
        }

        /// <summary>
        /// Требования к ПО
        /// </summary>
        /// <returns></returns>
        public IActionResult Demands()
        {
            ViewBag.RetFromLoginUrl = @"/Program/Demands/";
            return View();
        }

        /// <summary>
        /// Процесс разработки ПО
        /// </summary>
        /// <returns></returns>
        public IActionResult Implementation()
        {
            ViewBag.RetFromLoginUrl = @"/Program/Implementation/";
            return View();
        }
    }
}

src/Novtehprom.Web.Mvc/Controllers/WebsiteController.cs
using Microsoft.AspNetCore.Mvc;
using Novtehprom.Controllers;
using Novtehprom.Web.Mvc.Models;
using Novtehprom.WepPages.WebSites;

namespace Novtehprom.Web.Mvc.Controllers
{
    /// <summary>
    /// Отображение страницы Website
    /// </summary>
    public class WebsiteController : NovtehpromControllerBase
    {
        public WebsiteController(IWebSitesAppService webSitesAppService)
        {
            _webSitesAppService = webSitesAppService;

        }
        private readonly IWebSitesAppService _webSitesAppService;

        public async System.Threading.Tasks.Task<IActionResult> CostAsync()
        {
            var priceDto = await _webSitesAppService.GetPriceAsync();
            var model = new WebPriceViewModel(priceDto);
            ViewBag.RetFromLoginUrl = @"/Website/Cost/";
            return View(model);
        }
    }
}

src/Novtehprom.Web.Mvc/Views/Shared/Components/TenantChange/TenantChangeViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.AutoMapper;
using Abp.ObjectMapping;
using Novtehprom.Sessions;

namespace Novtehprom.Web.Mvc.Views.Shared.Components.TenantChange
{
    public class TenantChangeViewComponent : NovtehpromViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IObjectMapper _objectMapper;

        public TenantChangeViewComponent(ISessionAppService sessionAppService, 
            IObjectMapper objectMapper)
        {
            _sessionAppService = sessionAppService;
            _objectMapper = objectMapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var loginInfo = await _sessionAppService.GetCurrentLoginInformations();
            var model = _objectMapper.Map<TenantChangeViewModel>(loginInfo);
            return View(model);
        }
    }
}

src/Novtehprom.Web.Mvc/Views/Shared/Components/TopBarLanguageSwitch/TopBarLanguageSwitchViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Abp.Localization;

namespace Novtehprom.Web.Mvc.Views.Shared.Components.TopBarLanguageSwitch
{
    public class TopBarLanguageSwitchViewComponent : NovtehpromViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public TopBarLanguageSwitchViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public IViewComponentResult Invoke()
        {
            var model = new TopBarLanguageSwitchViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList()
            };

            return View(model);
        }
    }
}

src/Novtehprom.Web.Mvc/Views/Shared/Layout/_Footer.cshtml
<div class="row">
    <div class="col-12">
        @*<a href="https://webmaster.yandex.ru/siteinfo/?site=novtehprom.ru"><img width="88" height="31" alt="" border="0" src="https://yandex.ru/cycounter?novtehprom.ru&theme=light&lang=ru" /></a>*@
        <span class="ml-2">&copy; 2020 @L("CompanyName")</span>
    </div>
</div>

src/Novtehprom.Web.Mvc/Views/Shared/Layout/_Header.cshtml
@using Novtehprom.Web.Mvc.Views.Shared.Components.TopBarLanguageSwitch

<nav class="navbar navbar-expand-md">
    <a class="navbar-brand waves-effect" href="/">
        <img id="logoimg" src="@Url.Content("~/Images/Logo.jpg")" alt="" title=" @L("CompanyName")" />
    </a>
    <button class="navbar-toggler ml-auto waves-effect" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"><i class="fas fa-bars fa-1x"></i></span>
    </button>
    <div class="rightnavbutton waves-effect d-md-none">
        <a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="fas fa-ellipsis-v"></i></a>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav ml-auto">
            <li class="waves-effect"><a href="@Url.Action("Index","Contacts")"><i class="far fa-handshake"></i><span> @L("Contacts")</span></a></li>
            @if (Context.Request.HttpContext.User == null || !Context.Request.HttpContext.User.Identity.IsAuthenticated)
            {
                <li class="waves-effect"><a href="@Url.Action("Login","Account", new { returnUrl = (ViewBag.RetFromLoginUrl == null) ? "" : ViewBag.RetFromLoginUrl })"><i class="fas fa-sign-in-alt"></i><span> @L("LogIn")</span></a></li>
            }
            else
            {
                <li class="waves-effect"><a href="@Url.Action("Logout","Account", new { returnUrl = (ViewBag.RetFromLoginUrl == null) ? "" : ViewBag.RetFromLoginUrl })"><i class="fas fa-sign-out-alt"></i><span> @L("Logout")</span></a></li>
            }
            @await Component.InvokeAsync(typeof(TopBarLanguageSwitchViewComponent))
        </ul>
    </div>
    <div class="rightnavbutton waves-effect d-none d-md-inline-block">
        <a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="fas fa-ellipsis-v"></i></a>
    </div>
</nav>

src/Novtehprom.Web.Mvc/Views/Shared/Layout/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="@L("CompanyName")">
    <meta name="description" content="@ViewData["Description"]" )">
    <meta name="keywords" content="@ViewData["KeyWords"]">
    <title>@ViewData["Title"]</title>
    @await Html.PartialAsync("_Styles.cshtml")
    @RenderSection("styles", required: false)
</head>
<body>
    @await Html.PartialAsync("_Loader.cshtml")

    <header>
        @await Html.PartialAsync("_Header.cshtml")
    </header>

    <section>
        @await Html.PartialAsync("_Rightsitebar.cshtml")
    </section>

    <content>
        @RenderBody()
    </content>

    <footer class="border-top footer">
        @await Html.PartialAsync("_Footer.cshtml")
    </footer>

    @await Html.PartialAsync("_Scripts.cshtml")
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Novtehprom.Web.Mvc/Views/Shared/Layout/_Loader.cshtml
<div class="loader">
    <div class="loader-spinner-conteiner">
        <div class="spinner-border text-info" role="status">
            <span class="sr-only">@L("PleaseWait")</span>
        </div>
    </div>
</div>

src/Novtehprom.Web.Mvc/Views/Shared/Layout/_Rightsitebar.cshtml
<aside id="rightsidebar" class="right-sidebar">
    <div class="rightsitebarcont">
        <div id="right-navigatin" class="right-navigatin">
            <ul>
                <li class="waves-effect">
                    <a href="@Url.Action("Index", "Home")">
                        <p>
                            <span><i class="fas fa-home fa-2x mr-2"></i> @L("HomePage")..</span>
                        </p>
                    </a>
                </li>
                <li class="waves-effect">
                    <a href="@Url.Action("Cost", "Program")">
                        <p>
                            <span><i class="fas fa-comments-dollar fa-2x mr-2"></i> @L("ProgramCost")..</span>
                        </p>
                    </a>
                </li>
                <li class="waves-effect">
                    <a href="@Url.Action("Timeframe", "Program")">
                        <p>
                            <span><i class="fas fa-calendar-check fa-2x mr-2"></i> @L("ProgramTimeframe")..</span>
                        </p>
                    </a>
                </li>
                <li class="waves-effect">
                    <a href="@Url.Action("Quality", "Program")">
                        <p>
                            <span><i class="fas fa-thumbs-up fa-2x mr-2"></i> @L("ProgramQuality")..</span>
                        </p>
                    </a>
                </li>
                <li class="waves-effect">
                    <a href="@Url.Action("Demands", "Program")">
                        <p>
                            <span><i class="fas fa-sitemap fa-2x mr-2"></i> @L("ProgramDemands")..</span>
                        </p>
                    </a>
                </li>
                <li class="waves-effect">
                    <a href="@Url.Action("Implementation", "Program")">
                        <p>
                            <span><i class="fas fa-hammer fa-2x mr-2"></i> @L("ProgramImplementation")..</span>
                        </p>
                    </a>
                </li>
                <li class="waves-effect">
                    <a href="@Url.Action("Cost", "Website")">
                        <p>
                            <span><i class="fas fa-globe fa-2x mr-2"></i> @L("WebSite")..</span>
                        </p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</aside>

src/Novtehprom.Web.Mvc/Views/Shared/Layout/_Scripts.cshtml
<script src="https://kit.fontawesome.com/12b8083e53.js" crossorigin="anonymous"></script>
<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/jquery-slimscroll/jquery.slimscroll.js" asp-append-version="true"></script>
    <script src="~/lib/toastr/toastr.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert/dist/sweetalert.min.js" asp-append-version="true"></script>
    <script src="~/lib/waves/waves.es5.js"></script>
    <script src="~/lib/abp-web-resources/Abp/Framework/scripts/abp.js" asp-append-version="true"></script>
    <script src="~/lib/abp-web-resources/Abp/Framework/scripts/libs/abp.jquery.js" asp-append-version="true"></script>
    <script src="~/lib/abp-web-resources/Abp/Framework/scripts/libs/abp.toastr.js" asp-append-version="true"></script>
    <script src="~/lib/abp-web-resources/Abp/Framework/scripts/libs/abp.blockUI.js" asp-append-version="true"></script>
    <script src="~/lib/abp-web-resources/Abp/Framework/scripts/libs/abp.spin.js" asp-append-version="true"></script>
    <script src="~/lib/abp-web-resources/Abp/Framework/scripts/libs/abp.sweet-alert.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="~/js/layout.js" asp-append-version="true"></script>*@
</environment>
<environment names="Staging,Production">
    <script src="~/view-resources/Views/_Bundles/shared-layout.min.js"></script>
</environment>

src/Novtehprom.Web.Mvc/Views/Shared/Layout/_Styles.cshtml
<link rel="SHORTCUT ICON" href="/favicon.ico" type="image/x-icon">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

<environment names="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/lib/waves/waves.css" rel="stylesheet" />
    <link href="~/lib/famfamfam-flags/dist/sprite/famfamfam-flags.css" rel="stylesheet" />    
    <link rel="stylesheet" href="~/sass/site.css" />
</environment>

<environment names="Staging,Production">
    <link rel="stylesheet" href="~/view-resources/Views/_Bundles/shared-layout.min.css" />
    <!-- Yandex.Metrika informer -->
    <a href="https://metrika.yandex.ru/stat/?id=17499604&amp;from=informer"
       target="_blank" rel="nofollow">
        <img src="https://informer.yandex.ru/informer/17499604/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
             style="width:88px; height:31px; border:0; display:none" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" class="ym-advanced-informer" data-cid="17499604" data-lang="ru" />
    </a>
    <!-- /Yandex.Metrika informer -->
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
            (function (m, e, t, r, i, k, a) {
                m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) };
                m[i].l = 1 * new Date(); k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
            })
                (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

            ym(17499604, "init", {
                clickmap: true,
                trackLinks: true,
                accurateTrackBounce: true,
                webvisor: true
            });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/17499604" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</environment>